Deploy phase

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,8 +4,8 @@ on: push
 
 jobs:
   build:
-    runs-on: ubuntu-latest
-    steps:
+  runs-on: ubuntu-latest
+  steps:
     - name: checkout code
       uses: actions/checkout@v2
     - name: Build image
@@ -17,15 +17,15 @@ jobs:
       with:
         username: ${{ secrets.DOCKER_USERNAME }}
         password: ${{ secrets.DOCKER_PASSWORD }}
-  - name: Push image to registry
-    run: |
-      docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
-      docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+    - name: Push image to registry
+      run: |
+        docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
+        docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio
 
 deploy:
-    needs: build
-    runs-on: ubuntu-latest
-    steps:
+  needs: build
+  runs-on: ubuntu-latest
+  steps:
     - name: ssh to Linux and run container
       uses: appleboy/ssh-action@v1
       with:
@@ -33,7 +33,7 @@ deploy:
         username: ${{ secrets.SSH_USERNAME }}
         key: ${{ secrets.SSH_KEY_PAIR }}
         script: |
-            docker rm -f portfolio || echo "Container not found, skipping removal."
-            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
-            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+          docker rm -f portfolio || echo "Container not found, skipping removal."
+          docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
+          docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio
     
