Deploy phase

diff --git a/.github/workflows/ci.yml b/.github/workflows/ci.yml
--- a/.github/workflows/ci.yml
+++ b/.github/workflows/ci.yml
@@ -4,36 +4,36 @@ on: push
 
 jobs:
   build:
-  runs-on: ubuntu-latest
-  steps:
-    - name: checkout code
-      uses: actions/checkout@v2
-    - name: Build image
-      run: |
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }} .
-        docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio .
-    - name: Docker login
-      uses: docker/login-action@v2
-      with:
-        username: ${{ secrets.DOCKER_USERNAME }}
-        password: ${{ secrets.DOCKER_PASSWORD }}
-    - name: Push image to registry
-      run: |
-        docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
-        docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+    runs-on: ubuntu-latest
+    steps:
+      - name: checkout code
+        uses: actions/checkout@v2
+      - name: Build image
+        run: |
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }} .
+          docker build -t ${{ secrets.DOCKER_USERNAME }}/ciportfolio .
+      - name: Docker login
+        uses: docker/login-action@v2
+        with:
+          username: ${{ secrets.DOCKER_USERNAME }}
+          password: ${{ secrets.DOCKER_PASSWORD }}
+      - name: Push image to registry
+        run: |
+          docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
+          docker push ${{ secrets.DOCKER_USERNAME }}/ciportfolio
 
-deploy:
-  needs: build
-  runs-on: ubuntu-latest
-  steps:
-    - name: ssh to Linux and run container
-      uses: appleboy/ssh-action@v1
-      with:
-        host: ${{ secrets.HOST }}
-        username: ${{ secrets.SSH_USERNAME }}
-        key: ${{ secrets.SSH_KEY_PAIR }}
-        script: |
-          docker rm -f portfolio || echo "Container not found, skipping removal."
-          docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
-          docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio
+  deploy:
+    needs: build
+    runs-on: ubuntu-latest
+    steps:
+      - name: ssh to Linux and run container
+        uses: appleboy/ssh-action@v1
+        with:
+          host: ${{ secrets.HOST }}
+          username: ${{ secrets.SSH_USERNAME }}
+          key: ${{ secrets.SSH_KEY_PAIR }}
+          script: |
+            docker rm -f portfolio || echo "Container not found, skipping removal."
+            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio:${{ github.run_number }}
+            docker run -d --name portfolio -p 8080:80 ${{ secrets.DOCKER_USERNAME }}/ciportfolio
     
